language: java
sudo: required
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker login -u "anddopphoopha" -p "$DOCKER_PASSWORD"
- chmod +x mvnw
install:
- mvn install -Dmaven.javadoc.skip=true -B -V
- ls -l
- docker build --build-arg JAR_FILE=/target/project.jar -t anddopphoopha/project234-backend
  .
- docker push anddopphoopha/project234-backend
- docker pull dto80/project234-frontend:latest
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: BupQvygwPT6xnb0j67AXGLHB2TCRmXQejMu5fgxhrM4qJTbLESEnvzaTSEBfdxz3Ce6qwepOZY5gYa/3582lDLcPaWyHHkKzoybnmcRq/Js3XwdEAdlunVCoXjvVXdfMD06kXnbN5YQeJAylnNldJFkl9dZQ4jJTcr8Pr9xUk7uyZlHf0r9hD3DlA+SJCeHQjDX8dwKeCUD/5WZM0sm9NS4BbWP9GWnBKY0A1aB5HcMQsax8+0iVA8IVCumIB2Oex99Tih3QzQbPyFnvWsqWKr6Ph83nrmFjUhqyw9GkXG90i6dS1Ia2Tj6zO6d4+imWhhCKt0KXDrm19vUAemj4H1aMy89xkBkBW4F5tWXRNcGbJTRBPlHyBEuFL0S9vcIL1ruPb/LrW16/9Doqa5vSuYKt/wJZs7sGV3K3MwlXIrEQ0ApZYLVWt/GHQMZSQHfIzOr6yZ6XMhOawzJDGiMKiSjs2pHr7rG+I5XX5aWakolUCQBZ0IYMaW12NLmTpYgWfDX/IBjGchLyJQ46kKmLpur3NBRo99YYvSsyxn2tPnEbqYknzqXyGcGLdUj9+3KiqRprEJq0esvdLchRXCNfr6PkzISAx89pDxpgj4fUDHgH5my2dI7IjPg2Z2C5wbw4GPU4DhhhfsPO4DHE2yp5z68bM3+Ylh+zTpMDY5zrans=
  - secure: aEdgPrBWhKy9Vo3I3f8nAxQgSjuvDMsbcRswmPMvaw+HPDLCaDjV2G6oVYfY98qSZ8Hw9dGF63ZmYjTBY8jRN9SwIaCJ0lvrGSGhtk9XfNzAxpMFsksh0MJSRziCnHcANlkyvGIpZZa35UJo7Q/pZf/0nV2JU/205fjxRRW2eGkNwlj7bGJhrcHt6U1dXbMLGrPImxhdHS8Be30ZgCylIDU1VJgfYZIQaaSEBhfvrZ74bOp8Wlnumh1UzUBGsUFDOKD6UV1mTAnRuFJayvFFF2OlwTXuvF5mO8nF8dIBSEmW8iAZH8C0trBTWH4bmH7+RrMoM9NmF2VBH0+/cLeWuWgx/NYP+SzVRhjLwDfhOMQannnOHR3bRxuUlXCbvaa4nZjc6IUARuhoEGlTEKgXjY/8vmofWN5SHUo9R5HDr22R09XmvzMsDLw5CUPN90Pj1NKwTT/21zN+7fILu+rQ4hEoQ2Y8Lf75e9Tnwjf9miCH9p7rO02ibpLt4aoTHYV6XLegU2K2IpbKrCfT/EzZ1DDaa8uLVJ+L3dudMvfu1ypGx2grLT5x4LhH+esRJBZngA3/1irbS3YFUJUNFOWtqlWL5RGid3IyZ58wOu+nw/mmThCO7ixDxMKcRyzkJ9FbGdSUUzVrJwAbw6GFTX1c7Z4D4ToLH53FwH3epQlwfYI=
