version: '3.3'
services:
  backend:
    image: 
    ports: anddopphoopha/project234-backend:latest
      - "8086:8080"
    # volumes:
    #   - type: bind
    #     source: ./project/xxx
    #     target: /usr/share/nginx/assets
  frontend:
    image: dto80/project234-frontend:latest
    ports:
      - "8084:80"