version: '3.3'
services:
  backend:
    image: anddopphoopha/project234-backend:latest
    ports: 
      - "8086:8080"
    volumes:
      - type: bind
        source: /xxx
        target: /usr/share/nginx/assets
  frontend:
    image: dto80/project234-frontend:latest
    ports:
      - "8085:80"